--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OiranCage/Symmetrica
build-by-default: true
branches:
- main
projects:
  Symmetrica:
    path: ""
    libs:
      - src: CortexPE/Commando/Commando
        vendor: raw
...
